---
# tasks file for role/launch_ec2

- name: launch ec2 instance
  amazon.aws.ec2_instance:
   instance_type: "{{ec2_instance_type}}"
   image_id: "{{ec2_image_id}}"
   # key name
   region: "{{ec2_region}}"
   state: present







